### ISSUE TITLE
Error parsing NaiveTime from very short string

### ISSUE THREAD

**Issue by Toover** [chronotope/chrono#631] opened 2021-12-05 07:19 UTC
Hello, as far as I can tell, this is supposed to work:
```rust
chrono::NaiveTime::parse_from_str("2h", "%kh");
```
I expect the result to be a `NaiveTime` representing 2 o'clock.
Instead, I get a `ParseError(NotEnough)`.

Am I wrong or is the parsing wrong?

**Comment by cecton** [comment] 2022-03-28 16:38
Also having this issue with `%Y-%m-%dT%H:%M`... my guess is that it requires you to pass all the fields, it doesn't fallback to 0. So in your case you probably need to give `%kh:%M` with `2h00`

**Comment by djc** [comment] 2022-03-29 08:08
I think this is a duplicate of #191, do you agree?

**Comment by victorpaleologue** [comment] 2022-03-29 12:46
I do.

**Closed** 2022-03-29 12:56 UTC
