### ISSUE TITLE
Panic on macOS 10.12

### ISSUE THREAD

**Issue by fralonra** [chronotope/chrono#841] opened 2022-10-11 02:19 UTC
Hi, all.

The following minimum code panicked and I don't know why:

```rust
// main.rs

use chrono::prelude::*;

fn main() {
    let dt = Local::now();
}
```

panic message:
```
thread 'main' panicked at 'unable to select local time type: FindLocalTimeType("no local time type is available for the specified timestamp")'
```

from this line: https://github.com/chronotope/chrono/blob/45142764ab6e1f2957437aa187970b94d3aaeadc/src/offset/local/unix.rs#L132

**env**
- rustc    1.62.1 (e092d0b6b 2022-07-16)
- rustup  1.25.1 (bb60b1e89 2022-07-12)
- chrono 0.4.22
- macOS 10.12.1

**Comment by djc** [comment] 2022-10-11 07:45
So yes, I guess we might not "support" macOS 10.12 -- looks like that's been out of supported service for about 3 years at this point. If you can come up with a patch for it (and it doesn't add too much complexity) we'll consider fixing it. You can have a look at the file you referenced to get a feeling for what's going on.

**Comment by esheppa** [comment] 2022-10-11 10:12
It would also be useful to understand what is in the /etc/localtime file - a debug output of the parsed zone file should be sufficient to figure out what is going on.  @fralonra if you clone down the `chrono` source code you can use [`tz_info::TimeZone::from_file`](https://github.com/chronotope/chrono/blob/45142764ab6e1f2957437aa187970b94d3aaeadc/src/offset/local/tz_info/timezone.rs#L83) for this

**Comment by fralonra** [comment] 2022-11-11 06:28
Thanks for all!

I cloned the source code and found that the error was generated from:
https://github.com/chronotope/chrono/blob/d147e9a2152d1d961372bf5a6a261c644746efdf/src/offset/local/tz_info/timezone.rs#L174

I've also tried [`time`](https://github.com/time-rs/time) crate, and that crate worked as expected on the target machine.

**Comment by esheppa** [comment] 2022-11-14 10:31
Thanks @fralonra - could you show the `dbg!` output of the `self` type at the start of that function (`TimeZoneRef::find_local_time_type`)

**Comment by djc** [comment] 2022-12-09 14:16
@test9753 would you be able to figure out a PR for this? I probably won't have time to look into it (and can't easily test), would be happy to answer questions you have and/or review your code.

**Comment by jfro** [comment] 2023-07-24 16:35
looks like we've run into this with our users as well. we recently updating some our dependencies and that included our use of flexi_logger switching from `time` to `chrono`. We still support macOS 10.11+ as long as apple doesn't blow that up for us.

After some digging I've gotten it to reproduce, as it seems to depend on what time zone the system is, apparently it doesn't like certain ones? I'm normally `America/New_York` which is fine, but `America/Guayaquil` will cause the panic.

Not sure if sharing the /etc/localtime would help? I can try to dig into it more to see if we can figure it out, as so far I don't know exactly why that timezone is giving chrono grief yet.

![image](https://github.com/chronotope/chrono/assets/41898/e0079738-417b-4bf6-b9d1-fa134bbc148e)

**Comment by jfro** [comment] 2023-07-24 17:13
here's the compressed timezone file that /etc/localtime is symlinked to when I can reproduce the panic. The simple example above is what i was using. 0.4.19 doesn't panic but 0.4.20+ does if that's helpful.

[Guayaquil.zip](https://github.com/chronotope/chrono/files/12148321/Guayaquil.zip)

**Comment by pitdicker** [comment] 2023-07-24 17:19
Thank you! 0.4.20 is when we started to parse the file in chrono instead of depending on libc.

**Comment by jfro** [comment] 2023-07-24 17:38
np! let me know if you need anything else, looks like we can't roll back to 0.4.19 easily anyway so a fix will be the best way forward.

**Comment by jfro** [comment] 2023-07-24 18:50
In case it's helpful, I poked around some with v0.4.26 tag source of chrono to compare modern macOS tz file vs the one from 10.11, looks like the extra_rule path is taken on newer macOS. The newer macOS tz file has extra_rule, a few more transitions & local_time_types too. If you need/want a newer macOS tz file for Guayaquil I can upload too.

Also wish I could remember what I had to do to get the macOS 10.11 VM created, do recall it was a huge pain in the ass being such an old macOS. It's in Parallels on an intel mac I have for testing these kind of things, getting them running on a PC is even more of a pain too.

**Comment by pitdicker** [comment] 2023-07-25 11:42
@jfro Thank you, that file was very helpful. The missing extra_rule was indeed the problem.

Fixed in https://github.com/chronotope/chrono/pull/1201.

**Closed by pitdicker** 2023-07-25 11:42 UTC
Labels: panic

**Comment by pitdicker** [comment] 2023-07-25 14:18
Let us know if it works :smile:.

**Comment by jfro** [comment] 2023-07-26 14:33
oh it definitely does! thanks again! no more panic on the super old macOS systems.
