### ISSUE TITLE
Overriding the default padding behavior of numeric specifiers %? doesn't work

### ISSUE THREAD

**Issue by omayerg** [chronotope/chrono#513] opened 2020-12-03 13:38 UTC
According to [docs](https://docs.rs/chrono/0.4.15/chrono/format/strftime/index.html):

> %-? | Suppresses any padding including spaces and zeroes. (e.g. %j = 012, %-j = 12)

I tried to use this for month (%m) but the following panics on the first unwrap:

use chrono::format;

fn main() {
    let p = &mut format::Parsed::new();
    format::parse(p, "2014-005-25", format::StrftimeItems::new("%Y-%-m-%d")).unwrap();

    println!("{}", p.to_naive_datetime_with_offset(0).unwrap());
}

**Comment by robyoung** [comment] 2020-12-03 14:17
The `%-?` modifier suppresses padding defined on the field when formatting. The effect on parsing happens automatically. You can see in the playground link below that both `2014-5-25` and `2014-02-25` are parsed correctly.

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=10ce96b805ade82a6fa1d49c6eb805af)

**Comment by omayerg** [comment] 2020-12-03 16:56
Thanks for your answer, Rob!
From your example in the playground I suspect this is not what I'm trying to achieve. What I'm trying to achieve is to skip any symbol which is not a digits while parsing.
For example, I want this:

[#!@$$@#$#@$2020-11-11$@@T00:11:19.309Z]
To be parsed as:
2020-11-11 00:11:19.309

Do you think there is a way to achieve this in rust with chrono?

**Comment by robyoung** [comment] 2020-12-03 17:07
If you don't know what those extra characters are going to be then I'm afraid not. Maybe using a regular expression to look for this bits that you're interested in?

**Comment by omayerg** [comment] 2020-12-06 15:18
Isn't enough to know that those characters are non digits?
Regarding your suggestion, I'm sorry I'm not sure I understand, you mean manually? This can't be achieved in chrono?

**Comment by robyoung** [comment] 2020-12-06 17:27
I don't think it can I'm afraid.

**Comment by pitdicker** [comment] 2023-09-03 05:25
Closing an a duplicate of https://github.com/chronotope/chrono/issues/591 (although that issue is newer).

**Closed by pitdicker** 2023-09-03 05:25 UTC
Labels: parsing
