### ISSUE TITLE
Missing micros and millis "with" functions since 0.4.23

### ISSUE THREAD

**Issue by seerwill** [chronotope/chrono#1025] opened 2023-04-18 10:34 UTC
Prior to https://github.com/chronotope/chrono/pull/827 we could do:

```rust
chrono::Utc
    .ymd(year, month, day)
    .and_hms_micro(hour, minute, sec, micros)
```

The deprecation notice says to replace `ymd -> with_ymd_and_hms`. This obviously doesn't work directly `with_ymd_and_hms` has a different return type to `ymd`.

Also, the deprecation notice for `Date::and_hms_micro` incorrectly suggests to use `Date::and_hms_micro_opt` instead, however `Date` itself is deprecated so this doesn't seem right.

On the other hand there don't seem to be any `with_micro` or `with_milli` functions on `DateTime`, so I have to do:

```rust
chrono::Utc
    .with_ymd_and_hms(year, month, day, hour, minute, sec)
    .unwrap()
    .with_nanosecond(micros * 1_000)
    .unwrap()
```

Is there an "official" way to do this after 0.4.23?

**Comment by djc** [comment] 2023-04-18 10:43
I think the way we've been suggesting is to build a `NaiveDateTime` first, then add the timezone to it.

**Comment by pitdicker** [comment] 2023-07-21 11:17
Closing as a duplicate of https://github.com/chronotope/chrono/issues/873.

**Closed by pitdicker** 2023-07-21 11:17 UTC
