### ISSUE TITLE
^ the trait `Default` is not implemented for `chrono::Duration`

### ISSUE THREAD

**Issue by akaNightmare** [chronotope/chrono#1297] opened 2023-09-17 15:39 UTC
Hello, received an error, and I assume the default for chrono::Duration should be `Duration::zero()`, anyway I tried to wrap Duration into my struct and implement Default trait for that and have no luck.
Thanks
```rs
use serde::{Deserialize, Serialize};
use chrono::Duration;

#[derive(Debug, Serialize, Deserialize)]
struct MyStruct {
    #[serde(skip)]
    duration: Duration,
    f: i32,
}

fn main() {
    // Create an instance of MyStruct
    let my_struct = MyStruct {
        duration: Duration::minutes(30),
        f: 12,
    };

    // Serialize it to JSON
    let serialized = serde_json::to_string(&my_struct).unwrap();
    println!("Serialized: {}", serialized);

    // Deserialize from JSON
    let deserialized: MyStruct = serde_json::from_str(&serialized).unwrap();
    println!("Deserialized: {:?}", deserialized);
}

```

The error:
```
error[E0277]: the trait bound `chrono::Duration: Default` is not satisfied
 --> src/main.rs:6:5
  |
6 |     #[serde(skip)]
  |     ^ the trait `Default` is not implemented for `chrono::Duration`
```

**Comment by pitdicker** [comment] 2023-09-17 16:45
@akaNightmare For a long time we could not implement `Default`, because `chrono::Duration` was (depending on a feature flag) a re-export of time 0.1 `time::Duration`. A bit more than a week ago we made a release to change this, see https://github.com/chronotope/chrono/releases/tag/v0.4.30. This was a tricky release, but we haven't got negative feedback yet.

Hopefully soon https://github.com/chronotope/chrono/pull/1137 can be merged that adds features to `chrono::Duration` such as this.

For now closing as a duplicate of https://github.com/chronotope/chrono/issues/717.

**Closed by pitdicker** 2023-09-17 16:45 UTC
