### ISSUE TITLE
SystemTimeToTzSpecificLocalTime failed with: The parameter is incorrect. (os error 87)

### ISSUE THREAD

**Issue by andrewbanchich** [chronotope/chrono#651] opened 2022-02-17 23:49 UTC
We're getting a panic from chrono [here](https://github.com/chronotope/chrono/blob/main/src/sys/windows.rs#L97) when run on a Windows 2012 server:

```
thread '<unnamed>' panicked at 'SystemTimeToTzSpecificLocalTime failed with: The parameter is incorrect. (os error 87)',
/cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/sys/windows.rs:97:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\std\src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\core\src/panicking.rs:107:14
   2: chrono::sys::inner::time_to_local_tm
   3: <chrono::offset::local::Local as chrono::offset::TimeZone>::from_utc_datetime
   4: <chrono::datetime::DateTime<chrono::offset::local::Local> as core::convert::From<std::time::SystemTime>>::from
...
```

We debugged the `SystemTime` we were getting and it was:

```rust
SystemTime {
    intervals: 147221225472,
}
```

A normal `intervals` value (e.g. `132790361186042732`) is much larger.

I'm assuming there's something about this unusually short `SystemTime` that's causing chrono to panic.

**Comment by andrewbanchich** [comment] 2022-02-18 16:26
This seems to be an issue with something lower level having to do with Windows, so I'm going to close this.

We [opened an issue](https://github.com/microsoft/windows-rs/issues/1549) in the official `windows` crate repo.

**Comment by andrewbanchich** [comment] 2022-02-18 17:48
Actually, I'm reopening this since based on [the feedback](https://github.com/microsoft/windows-rs/issues/1549#issuecomment-1044861209) from that issue it looks like the problem might be more in chrono's domain.

**Comment by djc** [comment] 2022-03-23 04:16
I'm unable to test on Windows myself. I'd be happy to review any code changes that are supported with documentation and/or explanation why they improve the current situation, but I probably won't be able to work on this proactively.

Let me know if you need any guidance on how to fix chrono to support this scenario better.

**Comment by andrewbanchich** [comment] 2022-04-02 19:45
@annmarie-switzer should have the fix for this. Unfortunately, I don't have the code and also am unable to test on Windows.

**Comment by rgwood** [comment] 2022-07-25 05:21
Just adding some additional info:

We ([Nushell](https://github.com/nushell/nushell)) recently got a bug report where this panic was occurring when the user ran [`ls ~/Downloads`](https://www.nushell.sh/book/commands/ls.html) (which uses `chrono` for file modified times).

The culprit ended up being a file named `NUL` (which should not exist, cannot be created manually, and was probably created by some buggy third-party software; [`NUL` is a reserved name](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions)). To fix the issue the user just deleted the file.

**Comment by pitdicker** [comment] 2023-07-05 05:53
While https://github.com/chronotope/chrono/issues/1150 is a duplicate of this issue, it becomes a bit more specific on what to fix.
Closing this issue as a duplicate.

**Closed** 2023-07-05 05:53 UTC
Labels: panic
