### ISSUE TITLE
Conversion to/from `Duration` from std library.

### ISSUE THREAD

**Issue by dpc** [chronotope/chrono#58] opened 2016-01-18 05:45 UTC
RIght now the state of things is rather weird, where there are two different Duration types.

**Comment by marjakm** [comment] 2016-02-19 18:17
+1

**Comment by dbrgn** [comment] 2016-03-29 08:03
Could we switch from re-exporting the external `time::Duration` to using `std::time::Duration` directly?

**Comment by dtolnay** [comment] 2016-09-02 01:28
"pants23" and I just ran into this in #serde. The standard library `std::time::Duration` works with Serde but `time::Duration` (and therefore `chrono::Duration`) does not.

**Comment by lifthrasiir** [comment] 2016-09-02 02:16
This is a non-trivial breaking change that is planned in 0.3. In part, `std::time::Duration` is never negative while `time::Duration` allows negative; this requires minor but significant interface changes. For now you need to use [`time::Duration::{from,to}_std`](https://doc.rust-lang.org/time/time/struct.Duration.html#method.from_std) methods to convert between them.

**Comment by Procrat** [comment] 2017-05-27 05:19
I would like to be able to use the implementation of the Hash trait, which is defined for `std::time::Duration`, but which apparently is not available for `chrono::Duration`.

**Comment by mqudsi** [comment] 2017-08-02 18:10
Is it possible to drop `time::Duration` entirely now that there is a stable `std::time::Duration`? Is there a roadmap for std compatibility?

**Comment by H2CO3** [comment] 2017-08-06 16:10
@lifthrasiir What is the state of this? Chrono is already at 0.4 yet the usage of `oldtime::Duration` remains prevalent. Chrono is *the* library that provides a steady clock; it would be really good if it weren't a pain to use one of its core data types.

**Comment by 0xpr03** [comment] 2017-08-25 22:39
This really is a hassle now, I can't convert a NaiveTime to a Duration at all and the 0.4 broke my workaround (which was essentially to just do some meaningless calculation-function which returned the right type).

**Comment by pitdicker** [comment] 2023-09-18 12:51
Closing as a duplicate of https://github.com/chronotope/chrono/issues/497.

**Closed by pitdicker** 2023-09-18 12:51 UTC
