### ISSUE TITLE
overflow when adding duration to instant on armv7

### ISSUE THREAD

**Issue by xoac** [chronotope/chrono#343] opened 2019-09-18 09:01 UTC
I think [From](https://doc.rust-lang.org/std/convert/trait.From.html) implementation must not panic. But it looks like the panic is from chrono crate. See 13.
Noticed in chrono v0.4.6 and v0.4.9
```
thread 'tokio-runtime-worker-0' panicked at 'overflow when adding duration to instant', src/libcore/option.rs:1034:5
stack backtrace:
   0:   0x49ebd4 - backtrace::backtrace::libunwind::trace::hfe5db90796807973
                       at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1:   0x49ebd4 - backtrace::backtrace::trace_unsynchronized::hd8dacec68bc2ef8b
                       at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2:   0x49ebd4 - std::sys_common::backtrace::_print::h483f4e7616d047f8
                       at src/libstd/sys_common/backtrace.rs:47
   3:   0x49ebd4 - std::sys_common::backtrace::print::h4d76d7afffd427d1
                       at src/libstd/sys_common/backtrace.rs:36
   4:   0x49ebd4 - std::panicking::default_hook::{{closure}}::h38923ab52011325c
                       at src/libstd/panicking.rs:200
   5:   0x49e7b8 - std::panicking::default_hook::hfaadada83166639f
                       at src/libstd/panicking.rs:214
   6:   0x49f398 - std::panicking::rust_panic_with_hook::h841b5ff4d0fdd5df
                       at src/libstd/panicking.rs:477
   7:   0x49ef5c - std::panicking::continue_panic_fmt::hff745e885c8efe81
                       at src/libstd/panicking.rs:384
   8:   0x49ee48 - rust_begin_unwind
                       at src/libstd/panicking.rs:311
   9:   0x4c308c - core::panicking::panic_fmt::h2daf88b2616ca2b2
                       at src/libcore/panicking.rs:85
  10:   0x4c30f8 - core::option::expect_failed::h4b77ebe6e62ec3a1
                       at src/libcore/option.rs:1034
  11:   0x49c00c - core::option::Option<T>::expect::hbba8ef32c6fbb8f5
                       at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/option.rs:314
  12:   0x49c00c - <std::time::Instant as core::ops::arith::Add<core::time::Duration>>::add::h3d1c30b66ef71411
                       at src/libstd/time.rs:312
  13:    0xfbd1c - chrono::datetime::<impl core::convert::From<chrono::datetime::DateTime<Tz>> for std::time::SystemTime>::from::h258865dbb9633d96
  14:    0x4ccb0 - <futures::stream::fuse::Fuse<S> as futures::stream::Stream>::poll::hcd520421edfbd1d9
  15:    0x87c78 - <futures::future::map::Map<A,F> as futures::future::Future>::poll::h8a0fb0a5216a82e5
  16:    0xeed54 - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::he2ee05ee8622cb71
  17:   0x461ef4 - futures::task_impl::std::set::hf81cf2d46542712c
  18:   0x4616c8 - std::panicking::try::do_call::h26a7c1e716f6de5c
  19:   0x4a2330 - __rust_maybe_catch_panic
                       at src/libpanic_unwind/lib.rs:82
  20:   0x45f5b8 - tokio_threadpool::task::Task::run::h516b7f6f3ab73870
  21:   0x458c70 - tokio_threadpool::worker::Worker::run_task::h665e8e89a66a4a3e
  22:   0x458254 - tokio_threadpool::worker::Worker::run::h0cacdfe229cc2e16
  23:   0x43bd64 - std::thread::local::LocalKey<T>::with::hfe4fb079a57100d1
  24:   0x43bc20 - std::thread::local::LocalKey<T>::with::hdff05eeff60f0d14
  25:   0x43ba9c - tokio_reactor::with_default::h1a4303e096aab7fd
  26:   0x43d594 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h165c1f1655a06589
  27:   0x461588 - std::thread::local::LocalKey<T>::with::hf7a3bae703782e98
  28:   0x460fcc - std::thread::local::LocalKey<T>::with::h0ba9ff703e9fe5c3
  29:   0x462624 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4a4bc456f498f614
  30:   0x461724 - std::panicking::try::do_call::h4834cba46ec23306
  31:   0x4a2330 - __rust_maybe_catch_panic
                       at src/libpanic_unwind/lib.rs:82
  32:   0x45c380 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h0504d4460fa4ebbe
  33:   0x49264c - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h39151bdefabfbd34
                       at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  34:   0x4a1a7c - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hbf3c4212b055f640
                       at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  35:   0x4a1a7c - std::sys_common::thread::start_thread::hde860cdc57aa1df3
                       at src/libstd/sys_common/thread.rs:13
  36:   0x4a1a7c - std::sys::unix::thread::Thread::new::thread_start::hc961109081401597
                       at src/libstd/sys/unix/thread.rs:79
```

**Comment by quodlibetor** [comment] 2019-09-18 14:07
Do you know what scale of times you're working with?

I agree that `From` should not panic without an explicit warning in the docs for extremely uncommon situations, I will think harder about what the `impl From DateTime<..> for SystemTime` should look like, having an explicit failing case would help.

**Comment by xoac** [comment] 2019-09-18 22:38
It happens on armv7 musl linux target. But the program handle data with embedded devices that can have uninitialized time. There should be unix timestamp but on begin ( there could be data from whole i32 range. The problem with tokio is it hide the place where the panic begins so I have also a problem with tracking where it begins.

**Comment by quodlibetor** [comment] 2019-09-19 17:30
Oh so it could be a completely invalid time? Yes datetimes don't support the entire range of numbers, you should use one of the `_opt` suffix methods to construct the datetimes to begin with, after which it should work.

**Comment by xoac** [comment] 2019-09-24 16:35
Here you have a code that [panic on armv7](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=65af9e14967260864fdeb2c849d4651f) this don't panic on x86_64 (I guess it panic when usize has 32bits).

To test you can use [cross](https://github.com/rust-embedded/cross) project like this:
```
cross test --target armv7-unknown-linux-musleabihf
```

I think there should be a way to convert DateTime to SystemTime with Result. But I [couldn't find nothing in chrono doc](https://docs.rs/chrono/0.4.9/chrono/?search=SystemTime)

**Comment by quodlibetor** [comment] 2019-09-24 17:45
Thank you! Yeah we have a `From` impl but not a `TryFrom` because we support ancient rust. We could auto-support newer versions, though, which might make sense.

**Comment by quodlibetor** [comment] 2019-09-24 17:46
also we should maybe just add an inherent or extension method that implements that transition with failure.

**Comment by xoac** [comment] 2019-09-25 09:06
I am working on azure piplines that run tests on embeeded devices. Would you like add such CI?

**Comment by quodlibetor** [comment] 2019-09-25 15:07
Yes if you can write some code to run the tests I will be happy to set up the azure infrastructure to point at chrono, that would be great!

**Comment by pitdicker** [comment] 2023-06-07 06:17
I can no longer reproduce this specific issue with 
```
cross test --target armv7-unknown-linux-musleabihf
```

I think this is because musl 1.20, [released in feb 2020](https://www.openwall.com/lists/musl/2020/02/21/1), made all time values 64 bit:
> This release moves all 32-bit archs to 64-bit time_t, enabling them to represent times beyond January of 2038.

See also https://musl.libc.org/time64.html.

**Comment by pitdicker** [comment] 2023-06-07 06:20
Yet there are other systems like `armhf-gnu` that still have a 32-bit time. See the related issue for the standard library https://github.com/rust-lang/rust/issues/44394.

I suppose the best solution would be if the standard library would use 64-bit values independent of the target as proposed in that issue.

As an alternative, or in the meantime, we can add a `TryFrom` implementation.

**Comment by djc** [comment] 2023-06-07 08:11
Seems very niche. Let's wait until someone complains (again).

**Closed by djc** 2023-06-07 08:11 UTC
Labels: bug
