### ISSUE TITLE
parsing %s datetime format doesn't work

### ISSUE THREAD

**Issue by omayerg** [chronotope/chrono#456] opened 2020-07-21 02:40 UTC
This test case fails:
`let time = DateTime::parse_from_str("1595290884", "%s").unwrap();
`
why?

**Comment by quodlibetor** [comment] 2020-07-21 13:54
`DateTime` requires a timezone, you should use `NaiveDateTime`. Possibly we should make `%s` imply UTC, but I don't believe that that is technically correct.

**Comment by omayerg** [comment] 2020-07-23 14:54
@quodlibetor Sorry my bad. Parsing that format with [chrono::format::parse](https://docs.rs/chrono/0.4.7/chrono/format/fn.parse.html) doesn't work.

**Comment by quodlibetor** [comment] 2020-07-23 15:05
What code fails and in what way?

**Comment by quodlibetor** [comment] 2020-07-24 15:20
I think you still want a naive time, this works:

```rust
use chrono::format;

fn main() {
    let p = &mut format::Parsed::new();
    format::parse(p, "1595516865", format::StrftimeItems::new("%s")).unwrap();

    println!("{}", p.to_naive_datetime_with_offset(0).unwrap());
}
```

**Comment by omayerg** [comment] 2020-07-25 22:09
@quodlibetor How your unwrap work and in my code the dt.is_ok() condition isn't fulfilled?

**Comment by quodlibetor** [comment] 2020-07-25 23:36
Try unwrap to see the error message.

Also, the problem is probably in the `apply_default_values`, try printing the `parsed` object.

I don't think they the bug is in Chrono, I think you're mutating it in a weird way. I would like Chrono to always give good error messages, but you're throwing away the error message with the `is_ok()`, instead of looking at it.

**Comment by omayerg** [comment] 2020-07-27 12:39
@quodlibetor Thanks 👍

**Comment by quodlibetor** [comment] 2020-07-31 16:43
I'm going to close this since it seems like it's not a bug in chrono.

**Closed by quodlibetor** 2020-07-31 16:43 UTC

**Comment by quodlibetor** [comment] 2020-07-31 16:48
As an aside though I would be very happy to take a PR that implements whatever you've got going on behind that `DateTimeParser::apply_default_values(&mut parsed);` call.
