### ISSUE TITLE
format paniced

### ISSUE THREAD

**Issue by fengyangsi** [chronotope/chrono#1363] opened 2023-11-21 16:01 UTC
I use chrono to translate timestamp to ISO format string in wasm program. And panic when call format function.

There was code

```rust
use worker::*;
use chrono::NaiveDateTime;

#[event(fetch)]
async fn main(req: Request, env: Env, ctx: Context) -> Result<Response> {
    panic::set_hook(Box::new(|_| {
        worker::console_error!("panic!");
    }));
    // this line didn't panic
    let now = NaiveDateTime::from_timestamp_millis(Date::now().as_millis() as i64).unwrap();
    // this line panic - format function
    Response::ok(now.format("%Y-%m-%dT%H:%M:%S%.f%:z").to_string())
}
```

```rust
    //panic
    now.format("%Y-%m-%dT%H:%M:%S%.f%:z")
    //also panic
    now.format("%+")
```

Cargo.toml
```toml
# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.31"
worker = "0.0.18"

[profile.release]
lto = true
strip = true
codegen-units = 1
```

wrangler.toml
```toml
main = "build/worker/shim.mjs"
compatibility_date = "2023-11-20"

[build]
command = "worker-build"
#also panic when command = "worker-build --release"
```

**Comment by djc** [comment] 2023-11-21 16:11
What is the panic message?

**Comment by fengyangsi** [comment] 2023-11-21 16:29
> What is the panic message?

panic occurred: panicked at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/string.rs:2460:14:
a Display implementation returned an error unexpectedly: Error
panic occurred: panicked at library/std/src/panicking.rs:135:9:
cannot modify the panic hook from a panicking thread

there are code
```rust
use worker::*;
use chrono::NaiveDateTime;
use std::panic;
#[event(fetch)]
async fn main(req: Request, env: Env, ctx: Context) -> Result<Response> {
    panic::set_hook(Box::new(|panic_info| {
        console_error!("panic occurred: {panic_info}");
    }));
    let now = NaiveDateTime::from_timestamp_millis(Date::now().as_millis() as i64).unwrap();
    Response::ok(now.format("%Y-%m-%dT%H:%M:%S%.f%:z").to_string())
}
```

**Comment by djc** [comment] 2023-11-22 08:45
I'd like a full back trace, please -- I can't easily reproduce a WASM environment.

**Comment by fengyangsi** [comment] 2023-11-24 02:25
> I'd like a full back trace, please -- I can't easily reproduce a WASM environment.

Sorry but how to get full back trace?

I call ```panic::set_hook()``` and ```console``` panic_info, that's all it return.

**Comment by djc** [comment] 2023-11-24 08:47
Usually with a `RUST_BACKTRACE=1` environment variable, not sure how that works on WASM. Or maybe just get a clone of chrono and start wiring in some `println!()`s to figure out what code exactly is triggering the panic.

**Comment by davehorner** [comment] 2023-11-24 16:57
I tried creating a test.

```
#[cfg(test)]
#[test]
/// now.format should not panic
fn assert_panic_nowformat() {
    let now = NaiveDateTime::from_timestamp_millis(NaiveDate::now().as_millis() as i64).unwrap();
    let ret = now.format("%Y-%m-%dT%H:%M:%S%.f%:z").to_string();
}
```
error[E0599]: no function or associated item named `now` found for struct `Date` in the current scope
  --> tests\panics.rs:25:58
   |
25 |     let now = NaiveDateTime::from_timestamp_millis(Date::now().as_millis() as i64).unwrap();
   |                                                          ^^^ function or associated item not found in `Date<_>`
```

```
warning: use of deprecated struct `chrono::Date`: Use `NaiveDate` or `DateTime<Tz>` instead
```
Date::now() doesn't exist for me on windows, I haven't setup a WASM build yet.  I tried using NaiveDate::now() that also is not there.  I can't compile the code provided at least on windows anyway.

**Comment by djc** [comment] 2023-11-27 10:03
Well, that trace has no chrono stack frames, so it doesn't help much. :(

**Comment by pitdicker** [comment] 2023-11-27 10:37
Can you test it with `Response::ok(now.format("%Y-%m-%dT%H:%M:%S%.f").to_string())`?

I think the issue is `%:z`: `NaiveDateTime` does not have an offset that you can print.

**Comment by fengyangsi** [comment] 2023-11-27 11:40
> Can you test it with `Response::ok(now.format("%Y-%m-%dT%H:%M:%S%.f").to_string())`?
> 
> I think the issue is `%:z`: `NaiveDateTime` does not have an offset that you can print.

it works, didn't panic

**Comment by pitdicker** [comment] 2023-11-27 12:27
Thank you for testing. That would make this issue a duplicate of https://github.com/chronotope/chrono/issues/1096, and https://github.com/chronotope/chrono/issues/1127 has the plan to return an error instead of panicking.

In your case you just want to convert a Unix timestamp to RFC 3339 format? Than something like this should do the trick:
```rust
use chrono::{Utc, TimeZone};
let response_str = Utc.timestamp_millis_opt(1662921288000).unwrap().to_rfc3339();
```

**Closed** 2023-11-28 09:17 UTC
