### ISSUE TITLE
Serious Randomly Occurring Offset Bug

### ISSUE THREAD

**Issue by seriousbusinessuser** [chronotope/chrono#391] opened 2020-01-31 10:33 UTC
Some global state introduces random into  local `offset()`.
Normally with `TZ=Europe/Moscow` `Local.ymd(2000, 10, 29).and_hms(2, 0, 0)` has `+04:00` offset but when it's called within test context with *unused* `bug` variable it sometimes returns `+03:00` offset. 

It's easy to reproduce, create empty project, add `chrono` as depenedncy and create following test file:
```rust
use chrono::{ Local, TimeZone };

#[test]
fn t1() { test_bug(); }

#[test]
fn t2() { test_bug(); }

#[test]
fn t3() { test_bug(); }

#[test]
fn t4() { test_bug(); }

fn test_bug() {
    // If you remove this line then bug goes away.
    let bug = Local.ymd(2000, 11, 29).and_hms(2, 0, 0);

    let expected_time = Local.ymd(2000, 10, 29).and_hms(2, 0, 0);

    assert_eq!(expected_time.offset().to_string(), "+04:00");
}
```

And run it using following:
```bash
for n in {1..100}; do TZ=Europe/Moscow cargo test ; done
```

Expected:
Unused variable `bug` shouldn't affect anything.

Actual:
When `bug` variable is present random tests are failing. 

Setup:
- rustc 1.42.0-nightly (212b2c7da 2020-01-30) 
- rustc 1.42.0-nightly (859764425 2020-01-07)
- chrono 0.4.10

**Comment by quodlibetor** [comment] 2020-02-04 02:31
I cannot reproduce this on stable rust and macos. I've copied your code into a new cargo binary project and run it 10,000 times: `for n in {1..10000}; do TZ=Europe/Moscow cargo test  2&>1 | rg '^test.t.*FAI' ; echo -n '.' ; done` (and yeah that grep does show errors if I put an explicit panic in there)

What OS does this happen for you on? And what operating systems are you using?

**Comment by seriousbusinessuser** [comment] 2020-02-09 18:52
@quodlibetor Arch Linux(Linux 5.5.2).

**Comment by Patryk27** [comment] 2020-02-24 07:59
rustc 1.41 (current stable), 1.43 (current nightly) on Ubuntu w/ 5.3.0-40-generic, randomly fails too.

**Comment by martinrlilja** [comment] 2020-11-05 20:40
This seems to be a bit of an edge case in `mktime`. I was able to reproduce the problem with this code:

```rust
use chrono::{Local, TimeZone};

fn main() {
    // Swap the order of time_a and time_b to fix the bug.

    // Request a date with timezone offset +03:00
    let date_a = Local.ymd(2000, 11, 29);
    // Request a date with timezone offset +04:00
    let date_b = Local.ymd(2000, 10, 29);

    // Request a time with timezone offset +03:00
    let time_a = date_a.and_hms(2, 0, 0);
    // Request a time with *either* timezone offset +04:00 *or* +03:00.
    let time_b = date_b.and_hms(2, 0, 0);

    assert_eq!(time_a.to_string(), "2000-11-29 02:00:00 +03:00");
    assert_eq!(time_b.to_string(), "2000-10-29 02:00:00 +04:00"); // will fail
}
```

Run with:

```sh
TZ=Europe/Moscow cargo run
```

My guess is that the local time 2020-10-29 02:00:00 is ambiguous, since Moscow changed from summertime to standard time during that hour, so `mktime` doesn't really know if you are referring to the hour before the change or the one after. So instead `mktime` makes a guess based on the time you requested just before.

In the code above `date_a`, `date_b` and `time_a` are unambiguous, but the result of `time_b` will depend on the time zone of the previous resolved date or time. So in the code above `time_b` will have the time offset +03:00 because `time_a` has the same offset. If you instead move `let time_b` to be right after `let date_b`, `time_b` will get the same time zone as `date_b`: +04:00.

Both of these results are correct AFAIK, it's just that they might not be what you might expect.

As for solutions, it's possible to wrap the time conversions in a mutex lock and fix it that way, maybe not the most elegant solution though. Maybe https://github.com/chronotope/chrono-tz can be used instead, idk.

I'm on Ubuntu 20.04 and glibc 2.31-0ubuntu9. I didn't go into the source code of glibc, so all of this is guesswork, I might be entirely incorrect.

As an aside, I didn't check how `localtime_r` affects things, but it is also involved in the time conversion.

**Comment by pitdicker** [comment] 2023-04-17 17:00
Starting with chrono 0.4.23 the problematic method [`TimeZone::from_local_date()`](https://docs.rs/chrono/latest/chrono/offset/trait.TimeZone.html#method.from_local_date) was deprecated. At the creation of the `Date` with that method the timezone offset gets set to a fixed value. See the [documentation of `Date`](https://docs.rs/chrono/latest/chrono/struct.Date.html).

Rust generates the following warnings/suggestions for the last test program:
```
warning: use of deprecated associated function `chrono::TimeZone::ymd`: use `with_ymd_and_hms()` instead
 --> src/main.rs:7:24
  |
7 |     let date_a = Local.ymd(2000, 11, 29);
  |                        ^^^
  |
  = note: `#[warn(deprecated)]` on by default

warning: use of deprecated associated function `chrono::TimeZone::ymd`: use `with_ymd_and_hms()` instead
 --> src/main.rs:9:24
  |
9 |     let date_b = Local.ymd(2000, 10, 29);
  |                        ^^^

warning: use of deprecated associated function `chrono::Date::<Tz>::and_hms`: Use and_hms_opt() instead
  --> src/main.rs:12:25
   |
12 |     let time_a = date_a.and_hms(2, 0, 0);
   |                         ^^^^^^^

warning: use of deprecated associated function `chrono::Date::<Tz>::and_hms`: Use and_hms_opt() instead
  --> src/main.rs:14:25
   |
14 |     let time_b = date_b.and_hms(2, 0, 0);
   |                         ^^^^^^^
```

Applying the suggestions gives something like this:
```rust
use chrono::{Local, TimeZone};

fn main() {
    // Request a time with timezone offset +03:00
    let time_a = Local.with_ymd_and_hms(2000, 11, 29, 2, 0, 0);
    // Request a time with *either* timezone offset +04:00 *or* +03:00.
    let time_b = Local.with_ymd_and_hms(2000, 10, 29, 2, 0, 0);

    assert_eq!(time_a.latest().unwrap().to_string(), "2000-11-29 02:00:00 +03:00");
    assert_eq!(time_b.earliest().unwrap().to_string(), "2000-10-29 02:00:00 +03:00");
    assert_eq!(time_b.latest().unwrap().to_string(), "2000-10-29 02:00:00 +04:00");
}
```

The methods on `Local` still have access to the timezone information and give the correct result. You can even choose how to handle ambiguous cases like this one.

**Comment by pitdicker** [comment] 2023-04-17 17:01
I suppose the deprecation of the affected method allows this issue to be closed?

**Comment by djc** [comment] 2023-04-18 10:08
I don't think the method deprecations should enable us to close this issue. However, I believe this issue will have gone away with the Rust-based local timezone offset calculations that we introduced in 0.4.20 (I think?).

**Closed by djc** 2023-04-18 10:08 UTC
