### ISSUE TITLE
v0.4.21 patch upgrade breaks SGX builds

### ISSUE THREAD

**Issue by nhynes** [chronotope/chrono#770] opened 2022-08-10 17:52 UTC
`chrono v0.4.21` introduces a new default feature `clock` which transitively pulls in `iana-time-zone`, which [doesn't build on SGX](https://github.com/strawlab/iana-time-zone/blob/392c9dee3d844d897bbc5c276855aa5bceaf8fb6/src/platform.rs#L7). This PATCH version upgrade has caused a sever-incompatible change on the SGX target (and others for which iana-time-zone doesn't work).

I would suggest:
1. yanking v0.4.21
2. publishing v0.5.0 with the new feature+transitive dep

Until then, essentially all users of the SGX target via core crates such as [mbedtls](https://github.com/fortanix/rust-mbedtls/blob/master/mbedtls/Cargo.toml#L36) will need to carefully manage lockfiles, which isn't super fun.

https://github.com/chronotope/chrono/pull/767 thankfully fixes the problem. Hopefully the new patch version gets through okay.

**Comment by esheppa** [comment] 2022-08-11 11:49
Thanks for the report @nhynes and @rdeaton - and apologies for the breakage. It looks like we have a few options here:
* To avoid the cyclic dependency we could temporarily turn off `iana-time-zone` for macOS/iOS (at least until https://github.com/strawlab/iana-time-zone/pull/50 is merged)
* Yanking v0.4.21 sounds like a good idea to me, but potentially we could release the fixes as v0.4.22  - essentially the reason for yanking would be the semver incompatibility
* In the specific case of `mbedtls` it doesn't look like this is using `Local`, and in fact, it looks like the usage of `chrono` could be replaced by `SystemTime`

**Comment by djc** [comment] 2022-08-11 12:15
Sorry for the regression!

It seems like 0.4.20 would also be broken on SGX, and I don't think we're going to yank both -- and I'm guessing the audience for whom 0.4.21 improves things is much larger than the audience for whom it makes things worse. In this case I think we should just get a 0.4.22 out as soon as possible.

**Closed** 2023-06-06 18:33 UTC
