### ISSUE TITLE
Addition of variants for the Fixed enum in v0.4.23 is a breaking change

### ISSUE THREAD

**Issue by newpavlov** [chronotope/chrono#1151] opened 2023-06-23 10:15 UTC
#759 has added two enum variants to the `chrono::format::Fixed` enum. This enum is not marked as `#[non_exhaustive]`, thus it's a clear breaking change. It has caused downstream breakage, e.g. https://github.com/Alex-PK/chrono-locale/issues/5.

**Comment by pitdicker** [comment] 2023-06-23 10:46
True, that is unfortunate.

I don't think there is anything that can be done by now, removing them after 4 releases would also be a breaking change.

Maybe a solution here is to move away from the unmaintained chrono-locale, and use chrono with the `unstable-locales` feature?

(duplicate of https://github.com/chronotope/chrono/issues/899)

**Comment by djc** [comment] 2023-06-23 10:47
Sorry about that -- please continue the discussion in #899.

**Closed by djc** 2023-06-23 10:47 UTC
